import 'dart:convert';

import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../../../core/services/share_service.dart';
import '../../../../core/utils/formatters.dart';
import '../../../auth/presentation/profile/data_export.dart';
import '../../domain/report_builder.dart';

/// CSV and PDF export of a [ReportData] via the native share sheet.
abstract final class ReportExporter {
  static String _file(ReportData r, String ext) =>
      'landowner-${r.type.name}-${r.period.from.year}${r.period.from.month.toString().padLeft(2, '0')}.$ext';

  static Future<void> csv(ReportData r) {
    final rows = <List<Object?>>[
      ['LandOwner', r.type.label, r.period.label, r.period.range],
      [],
      ['Income', r.income, 'Expenses', r.expense, 'Net', r.net],
      [],
      ['Item', 'Detail', ...r.columns],
      for (final row in r.rows)
        [row.label, row.sub, for (var i = 0; i < row.values.length; i++) r.percentColumns.contains(i) ? row.values[i] / 10 : row.values[i]],
      if (r.note.isNotEmpty) ...[[], [r.note]],
    ];
    return ShareService.bytes(utf8.encode(toCsv(rows)), _file(r, 'csv'), subject: r.type.label);
  }

  static Future<void> pdf(ReportData r) async {
    final regular = pw.Font.ttf(await rootBundle.load('assets/fonts/Manrope-Regular.ttf'));
    final bold = pw.Font.ttf(await rootBundle.load('assets/fonts/Manrope-ExtraBold.ttf'));
    const ink = PdfColor.fromInt(0xFF111830), blue = PdfColor.fromInt(0xFF304BC7), muted = PdfColor.fromInt(0xFF6B7186);
    const tint = PdfColor.fromInt(0xFFF3F6FE), line = PdfColor.fromInt(0xFFE4E8F4);
    // PDF fonts lack "Rs" ligature issues; use plain ASCII minus.
    String m(num v) => Money.compact(v).replaceAll('−', '-');
    pw.Widget fig(String l, String v) => pw.Expanded(
          child: pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
            pw.Text(l, style: pw.TextStyle(font: regular, fontSize: 9, color: PdfColors.white)),
            pw.SizedBox(height: 3),
            pw.Text(v, style: pw.TextStyle(font: bold, fontSize: 16, color: PdfColors.white)),
          ]),
        );

    final doc = pw.Document(title: r.type.label, author: 'LandOwner');
    doc.addPage(pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(36),
      theme: pw.ThemeData.withFont(base: regular, bold: bold),
      build: (_) => [
        pw.Text('LandOwner', style: pw.TextStyle(font: bold, fontSize: 12, color: blue)),
        pw.SizedBox(height: 6),
        pw.Text(r.type.label, style: pw.TextStyle(font: bold, fontSize: 24, color: ink)),
        pw.Text('${r.period.label} · ${r.period.range}', style: pw.TextStyle(fontSize: 10, color: muted)),
        pw.SizedBox(height: 18),
        pw.Container(
          padding: const pw.EdgeInsets.all(16),
          decoration: pw.BoxDecoration(color: blue, borderRadius: pw.BorderRadius.circular(14)),
          child: pw.Row(children: [fig('Income', m(r.income)), fig('Expenses', m(r.expense)), fig('Net cash flow', m(r.net))]),
        ),
        pw.SizedBox(height: 18),
        pw.TableHelper.fromTextArray(
          headers: ['Item', ...r.columns],
          data: [
            for (final row in r.rows)
              ['${row.label}${row.sub.isEmpty ? '' : '\n${row.sub}'}', for (var i = 0; i < row.values.length; i++) r.cell(i, row.values[i]).replaceAll('−', '-')],
          ],
          headerStyle: pw.TextStyle(font: bold, fontSize: 10, color: ink),
          cellStyle: pw.TextStyle(fontSize: 9, color: ink),
          headerDecoration: const pw.BoxDecoration(color: tint),
          rowDecoration: const pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(color: line))),
          cellAlignments: {for (var i = 1; i <= r.columns.length; i++) i: pw.Alignment.centerRight},
          border: null,
        ),
        if (r.note.isNotEmpty) ...[pw.SizedBox(height: 10), pw.Text(r.note, style: pw.TextStyle(fontSize: 9, color: muted))],
        pw.SizedBox(height: 18),
        pw.Text('Generated by LandOwner from your recorded data.', style: pw.TextStyle(fontSize: 8, color: muted)),
      ],
    ));
    await ShareService.bytes(await doc.save(), _file(r, 'pdf'), subject: r.type.label);
  }
}
