// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_0gPhwu9awf1BckbDityhy36-38MURjg',
    appId: '1:341447303427:web:017eec2825769a40528936',
    messagingSenderId: '341447303427',
    projectId: 'landowner-e2c4b',
    authDomain: 'landowner-e2c4b.firebaseapp.com',
    storageBucket: 'landowner-e2c4b.firebasestorage.app',
    measurementId: 'G-4E1F8P27JF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC-Dr2xEvWWYnCkC9i7wcrdki9LW2YP38',
    appId: '1:341447303427:android:78d3a8f1443b05ba528936',
    messagingSenderId: '341447303427',
    projectId: 'landowner-e2c4b',
    storageBucket: 'landowner-e2c4b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKj7_7XI9XPCfs1kn6SPFQTR9mJi5JYPg',
    appId: '1:341447303427:ios:3521c4598de2b8ae528936',
    messagingSenderId: '341447303427',
    projectId: 'landowner-e2c4b',
    storageBucket: 'landowner-e2c4b.firebasestorage.app',
    androidClientId: '341447303427-kh16tmugmc2hd6vg9aggie9no5m9cie5.apps.googleusercontent.com',
    iosClientId: '341447303427-43n0d06ak8pn85vma729kabv9jrn0par.apps.googleusercontent.com',
    iosBundleId: 'com.veradostudio.land-owner',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKj7_7XI9XPCfs1kn6SPFQTR9mJi5JYPg',
    appId: '1:341447303427:ios:3521c4598de2b8ae528936',
    messagingSenderId: '341447303427',
    projectId: 'landowner-e2c4b',
    storageBucket: 'landowner-e2c4b.firebasestorage.app',
    androidClientId: '341447303427-kh16tmugmc2hd6vg9aggie9no5m9cie5.apps.googleusercontent.com',
    iosClientId: '341447303427-43n0d06ak8pn85vma729kabv9jrn0par.apps.googleusercontent.com',
    iosBundleId: 'com.veradostudio.land-owner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_0gPhwu9awf1BckbDityhy36-38MURjg',
    appId: '1:341447303427:web:8b408a4d45ac2464528936',
    messagingSenderId: '341447303427',
    projectId: 'landowner-e2c4b',
    authDomain: 'landowner-e2c4b.firebaseapp.com',
    storageBucket: 'landowner-e2c4b.firebasestorage.app',
    measurementId: 'G-T2Q8W72MS6',
  );
}
